### ISSUE TITLE
Etherscan

### ISSUE THREAD

**Issue by GoJackzi** [The-Poolz/Poolz-Back#100]
**Describe the bug**
Etherscan TX lag

**To Reproduce**
Create/Join any pool, and on Metamask it says TX complete, but it takes a few minutes to show on etherscan.

**Expected behavior**
Etherscan should've been showing the pending tx and confirmed tx.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: WINDOWS 10
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**

**Wallet address**
0x34d4ECD77D6378EbddA1C62A38881E4587109181

**Comment by Lomet** [comment]
Each app waiting for a different amount of blocks to confirm the action.
and we are not controlling Etherscan.
