### ISSUE TITLE
Zero ratio

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#101]
**Describe the bug**
You are able to select a 0 ratio when creating a new pool

**To Reproduce**
1. click create new pool
2. enter contract details
3. enter 0 in Swap Ratio

**Expected behavior**
Should be a message 'Must be 0.0001 or higher' or something similar

**Screenshots**
<img width="1273" alt="Screenshot 2021-01-07 at 11 23 21" src="https://user-images.githubusercontent.com/39380100/103887438-f0eba600-50da-11eb-9eca-72f43682c3f8.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12
 - Browser Firefox
 - Version 83

**Additional context**
Metamask connected on Rinkeby

**Wallet address**
0xD4E5e3e9f936a59568C3A7c6159c5cFCE328D496

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/35

this is the issue for values in the join dialog.

thanks for the report.
