### ISSUE TITLE
Reject new pool leaves you in limbo

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#103]
**Describe the bug**
When creating a new pool and rejecting the transaction in metamask you are sent back to a page where it's unclear what to do. The CTA at the bottom isn't clickable. Perhaps you could be sent back to stage 2 with the confirm button. Otherwise you have to guess where to go next.

**To Reproduce**
1. Create New Pool
2. Enter details
3. Click confirm
4. Reject in metamask

**Expected behavior**
Should send you back to step 2 automatically or at least a new button to take you back to step 2

**Screenshots**

https://user-images.githubusercontent.com/39380100/103887846-aa4a7b80-50db-11eb-9963-76fff429b914.mov

**Desktop (please complete the following information):**
 - OS: MacOS 10.14
 - Browser Chrome and Firefox
 - Version: various

**Additional context**
Metamask connected via rinkeby

**Wallet address**
0xD4E5e3e9f936a59568C3A7c6159c5cFCE328D496

**Comment by crypto-x-soldier** [comment]
#58 Same thing happening in locked pool as well..

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/35

we got this issue for the join dialog.
