### ISSUE TITLE
Empty Values

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#104]
**Describe the bug**
Joining a pool with empty values sends you back to the dashboard without a message or error.

**To Reproduce**
1. Click join
2. Do not enter any values
3. Submit

**Expected behavior**
Should stay on screen with an error message, or perhaps the pools page should default to 0 on both fields instead of empty fields

**Screenshots**

https://user-images.githubusercontent.com/39380100/103900998-6f067780-50f0-11eb-8d15-a73ffe288486.mov

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Chrome and Firefox
 - Version Various

**Additional context**
Connected via Metamask

**Wallet address**
0xD4E5e3e9f936a59568C3A7c6159c5cFCE328D496

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/35

thanks for the report.
