### ISSUE TITLE
Bug. I can't paste ETH adress when i try to create pool

### ISSUE THREAD

**Issue by Smeilz** [The-Poolz/Poolz-Back#108]
**Describe the bug**
I can't paste ETH adress when i try to create pool

**To Reproduce**
1. Go to  https://app.poolz.finance/lockeddeal
2. Click on 'Token contract adress'
3. CTRL+C my ETH adress
4. CTRL+V and ...nothing happened
5. Right click+V and ...nothing happened
6. If i try print letter or number CTRL+V is working ok.

**Expected behavior**
CTRL+V and paste adress

**Screenshots**
Ihttps://ibb.co/zNqJspw

**Desktop (please complete the following information):**
 - OS: [wndows]
 - Browser [chrome,]
 - Version [v 87.0.4280.141 (Official build), (64 bit)]

**Wallet address**
ERC20 wallet
0x87e4639f2cd294ae7355aac2445D56FB36A17573

**Comment by Lomet** [comment]
> CTRL+C my ETH address
Need to copy the token address

more info here: 
https://github.com/The-Poolz/Poolz-Back/issues/23
