### ISSUE TITLE
Bug with with pool mapping and different numbers in dashboard

### ISSUE THREAD

**Issue by Smeilz** [The-Poolz/Poolz-Back#109]
**Describe the bug**
Bug with with pool mapping. After Joining Pool and sending ETH i didn't see some indicators that Pool finish.
According to the video, it is noticeable that the ether is written off and then the pool does not increase - this happens with a long delay and the user is not notified that the operation was successful or not successful.
In additional i see different data in my investment(0.1 eth) and created pool(2.5)

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on 'join' 
3. Click on 'continue' 
3. Click on 'swap 0.05 ETH to 0,5 Pool' ( You can see decimal point from ETH is point, bot in Poolz decimal point is  comma. I think this is not good)
4. Finish swap in Metamask
5. According to the video, it is noticeable that the ether is written off and then the pool does not increase - this happens with a long delay and the user is not notified that the operation was successful or not successful.
In additional i see different data in my investment(0.1 eth) and created pool(2.5)

**Expected behavior**
Notification that the operation was successful.
+The same amount in My investmens and created Poolz

**Screenshots**
https://drive.google.com/file/d/1d3RCLjYs8XV99pWy9P4KihMYJH3_-hh9/view
1. https://ibb.co/zJc2Lvp
2. https://ibb.co/VQjfzXb

**Desktop (please complete the following information):**
OS: [wndows]
Browser [chrome,]
Version [v 87.0.4280.141 (Official build), (64 bit)]

**Additional context**

**Wallet address**
0x87e4639f2cd294ae7355aac2445D56FB36A17573

**Comment by Lomet** [comment]
my investment section is not updated well
here more info:
https://github.com/The-Poolz/Poolz-Back/issues/24

thanks for the report.

**Comment by Smeilz** [comment]
@Lomet Do you think this is not a bug? Or do you mean that this was taken into account in #24  In my opinion, there is a slightly different situation.

**Comment by Lomet** [comment]
I'm sorry, let me add more info:
_I was in hurry to close all - now we can chat._

in the video - we see that the join dialog fails. but the "join" still flashes.
one of the issues links to #24 - talking about checking the values on the dialog that will fix this bug.
About the message is a good idea - so it's more an enhancement.

About the photos - My investments got some updating bug, that will be fixed for #24 (I did not check if no one else invested ...)
you right, slightly different situation but the fix from there will fix this.

Every report help us - Thanks.

**Comment by pravpit2019** [comment]
> I'm sorry, let me add more info:

Okay, thanks for the answer. Does this improvement fall into the general table? And will there be a summary table of results?
