### ISSUE TITLE
Bug with Disappearing Pool

### ISSUE THREAD

**Issue by Smeilz** [The-Poolz/Poolz-Back#110]
**Describe the bug**

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Creating Pool
3. See my Pool https://app.poolz.finance/myPools
4. Try to change wallet on tomochain
5.Pool disappeared

**Expected behavior**
The pool should be visible after switching and reconnecting the wallet. It can be disconnected for example due to the fact that the Internet is lost.

**Screenshots**
Video
https://drive.google.com/file/d/1dhi0PocqMG3k2VlJl2VMD7I0qlQ78KfI/view

**Desktop (please complete the following information):**
 OS: [wndows]
Browser [chrome,]
Version [v 87.0.4280.141 (Official build), (64 bit)]

**Additional context**

**Wallet address**
0x87e4639f2cd294ae7355aac2445D56FB36A17573

**Comment by Lomet** [comment]
When you go for another chain. its disconnects the wallet in order to connect to another one.
When the wallet is disconnected, poolz can't see what address you got, so can't show the information.
the information is always there, on the blockchain.
