### ISSUE TITLE
Locked Deals not visible on TomoChain Bug

### ISSUE THREAD

**Issue by iSkylark** [The-Poolz/Poolz-Back#116]
**Describe the bug**
Locked Deals on the menu on the left are not visible on TomoChain and MoonBeam tabs. They only show up on Ethereum tab.

**To Reproduce**
1. Go to 'https://app.poolz.finance/dashboard'
2. Click on 'TomoChain'
3. See bug - 'Locked Deals' disappear from menu on the left.

**Expected behavior**
Locked Deals should remain on menu on the left side, to allow users to Add Locked Deals on TomoChain and MoonBeam.

**Screenshots**
<img width="478" alt="locked deals not visible on tomochain" src="https://user-images.githubusercontent.com/77087043/103976838-c705b280-51b2-11eb-803b-73a99a97207a.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87

**Wallet address**
0xC229eaB0B6D74E9D8BE4CCF4b22FBC7a46DCaE78

**Comment by Lomet** [comment]
thanks for the report.
The current test is not for a locked deal. we did not upload it to tomochain (yet)
