### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by cryptoloverRobiul** [The-Poolz/Poolz-Back#12]
**Describe the bug**
After clinking Join button and Continue then system says " You have not enough poolz, Buy poolz and start make some money"

**To Reproduce**
1. Go to 'Join'
2. Click on 'Continue'
3. See error: You have not enough poolz, Buy poolz and start make some money

**Expected behavior**
There should have to by ETH or Swap

**Screenshots**
https://i.ibb.co/dtWjSSC/Capture.png

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [ 87.0.4280.88 (64-bit)]

**Additional context**
None

**Wallet address**
ERC20 wallet : 0x612E86E40ac3E40a2C0D33808AEb2cc28251B61f

**Comment by Lomet** [comment]
you can get a test POOLZ Token: 0x200944BB9427bBdcDB36d15A8e29CfF7083C03E7
on uniswap: app.uniswap.org
