### ISSUE TITLE
Bug. Disconnect wallet  after watching contract address

### ISSUE THREAD

**Issue by Smeilz** [The-Poolz/Poolz-Back#121]
**Describe the bug**
Don't stay on the Poolz page and disconnect wallet  after watching contract address

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on 'join test token'
3. click for watch contract address
4. Back on the page
5. Wallet was disconnected

**Expected behavior**
Contract address open in a new window and i can easy back on Poolz tab.

**Screenshots**
https://drive.google.com/file/d/1VROdON03p8Y_tlcLeZDJaku9pcxN4U_N/view

Desktop (please complete the following information):
OS: [wndows]
Browser [chrome,]
Version [v 87.0.4280.141 (Official build), (64 bit)]

Additional context

Wallet address
0x87e4639f2cd294ae7355aac2445D56FB36A17573

**Comment by Lomet** [comment]
Thanks for the report, the main issue is here: https://github.com/The-Poolz/Poolz-Back/issues/44
