### ISSUE TITLE
Bug. Can't search by contract address

### ISSUE THREAD

**Issue by Smeilz** [The-Poolz/Poolz-Back#122]
**Describe the bug**
Can't search by contract address

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on contract address
3. Click to copy and paste in search
4. See 'nothing'

**Expected behavior**
See pool contract address

**Screenshots**
https://drive.google.com/file/d/1y7i0pzTeFSrywKkJs3u4juGIt-72NtWn/view

Desktop (please complete the following information):
OS: [wndows]
Browser [chrome,]
Version [v 87.0.4280.141 (Official build), (64 bit)]

Additional context

Wallet address
0x87e4639f2cd294ae7355aac2445D56FB36A17573

**Comment by Lomet** [comment]
thanks for the report, the main ticket: https://github.com/The-Poolz/Poolz-Back/issues/34
