### ISSUE TITLE
Typing in a period/point followed by a number without the period/point

### ISSUE THREAD

**Issue by cliffordtcw2021** [The-Poolz/Poolz-Back#123]
When purchasing from a pool or creating a pool, if the user types in a period or point prior to a whole number in any of the number fields, the period is dropped.  While not a huge error, this will result in user frustration and unnecessary support requests.  

**To Reproduce**
See Video

**Expected behavior**
When typing in a period/point prior to a number that the same number is returned.  

https://user-images.githubusercontent.com/77163059/104035651-05da3f00-5198-11eb-8729-cd12d4c07792.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 87.0.4280.141 (Official Build) (64-bit)
 - 
**Additional context**
Small issue, but it will save your team time and money in the future while decreasing user frustration.

**Wallet address**
0x0FC02f75BcaD9CC70Ee16f79Fa58Fb9ADB5dACbf

**Comment by Lomet** [comment]
thanks for the report. the track all join dialog to here: https://github.com/The-Poolz/Poolz-Back/issues/35
