### ISSUE TITLE
CRITICAL BUG - Does not Work via Metamask Mobile IOS

### ISSUE THREAD

**Issue by cliffordtcw2021** [The-Poolz/Poolz-Back#124]
**Describe the bug**
After selecting join pool, entire UI does not work when logged in through iphone metamask mobile ios applicatoin.  If you select Open In browser you cannot connect the Metamask at all.

**To Reproduce**
1.  How to get to metamask browser:  https://user-images.githubusercontent.com/77163059/104051273-835c7a00-51ad-11eb-93f9-050b335868f7.mp4
2.  Example of it not working:  https://user-images.githubusercontent.com/77163059/104050160-cddcf700-51ab-11eb-8768-2febc9d2ff6d.mp4
3.  Not working if you select Open in Browser/cannot connect wallet at all from this:  https://user-images.githubusercontent.com/77163059/104051979-9e7bb980-51ae-11eb-8072-3556eb31da6e.mp4

**Expected behavior**
To be able to join pool via iphone using Metamask Wallet.

**Screenshots**
See videos.

**Desktop (please complete the following information):**
 - OS: iPhone Xr Model Software Version 14.2
 - Browser:  Metamask internal browser through ios metamask app  / Browser 2:  safari (version same as ios)
 - Version MetaMask v1.0.8 (554) 

**Additional context**
Many people will attempt to purchase via metamask app on iphone.  This is a CRITICAL error.  I have walked people through this process for other similar pools.   

**Wallet address**
0x0FC02f75BcaD9CC70Ee16f79Fa58Fb9ADB5dACbf

**Comment by Lomet** [comment]
Mobile support will come in a later stage.
thanks for the report.
