### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Tibicredo** [The-Poolz/Poolz-Back#13]
**Describe the bug**
When i want to creat a Pool, at the first window "1.Token Information", I`m not able to paist my copied Token Contract Adress. It is only able to wirte the letters in the box. 

When one letter is in, that I`m alble to copy the adress in the box. 

**To Reproduce**
1. Go to Creat a pool; 1. Token Information 
2. Copy your contact adress and paist it into the box of "Token Contract Adress"
3. This is not possible. 
4. Then try to fill in one letter and try to paist your adress again. Now it should go, but the first letter can not deleted. 

I hope i could do a litte help for this awesome project!

Desktop (please complete the following information):

OS: [Windows 10]
Browser [brave]
Version [ 1.18.77 Chromium: 87.0.4280.101 ]

**Wallet address**
ERC20 wallet for POZ rewards:
0xAdc449969C9E487691E3d1646638A94cCa8df089

**Comment by Lomet** [comment]
What address did you want to use as Token Contract Address?

**Comment by Tibicredo** [comment]
This adress: 

0xAdc449969C9E487691E3d1646638A94cCa8df089

**Comment by Lomet** [comment]
it is not working - it, not a token: https://rinkeby.etherscan.io/address/0xAdc449969C9E487691E3d1646638A94cCa8df089
need to input Token contract address
like:
POOLZ Token: 0x200944BB9427bBdcDB36d15A8e29CfF7083C03E7
Test Token: 0xe606c5CF639628Ae69F391aeA32eE3D347De86A8

**Comment by Tibicredo** [comment]
Ah ok, now it works! Thanks!

Regards Phil
