### ISSUE TITLE
Bug. Ipad didn't connect wallet

### ISSUE THREAD

**Issue by Smeilz** [The-Poolz/Poolz-Back#131]
**Describe the bug**
Ipad 7 generation didn't connect Metamask.

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on 'connect wallet' and nothing happened

**Expected behavior**
Connect wallet Metamask

**Screenshots**
https://ibb.co/MRBLwwc

**Desktop (please complete the following information):**
 - Ipad OS 14.1
 - Browser Chrome
 - Version 87.0.4280.77

**Wallet address**
0x87e4639f2cd294ae7355aac2445D56FB36A17573

**Comment by Lomet** [comment]
We will add mobile (non-desktop) support in a later patch.

thanks for the report
