### ISSUE TITLE
Bug. Didn't see the names of the important buttons (poorly visible font)

### ISSUE THREAD

**Issue by Smeilz** [The-Poolz/Poolz-Back#132]
**Describe the bug**
Didn't see the names of the important buttons (poorly visible font)

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on 'join'
3. Click on continue

**Expected behavior**
A bright, clear font with a hint about what will happen if you click on the button, whether ETH will be debited.

**Screenshots**
https://ibb.co/8DW4bdj
https://ibb.co/Gc09tsP
https://ibb.co/fSSXLRp

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Browser Chrome
 - Version [87.0.4280.88]

Wallet address
0x87e4639f2cd294ae7355aac2445D56FB36A17573

**Comment by Lomet** [comment]
Thanks for the report.
here the first: https://github.com/The-Poolz/Poolz-Back/issues/18
