### ISSUE TITLE
Bug with creating pool on MacOS

### ISSUE THREAD

**Issue by Smeilz** [The-Poolz/Poolz-Back#133]
**Describe the bug**

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on 'Create pool
3. Can't put token name, token symbol, can't paste erc20 adress press CTRL+V or right click-->paste

**Expected behavior**
I can choose token name, symbol, paste erc20 address for creating pool

**Screenshots**
https://ibb.co/sjCtWNg

Desktop (please complete the following information):
OS: MacOS Catalina 10.15.7
Browser Chrome
Version [87.0.4280.88]

Wallet address
0x87e4639f2cd294ae7355aac2445D56FB36A17573

**Comment by Lomet** [comment]
Thanks for the report. please fill in all the fields.
Check out this issue: https://github.com/The-Poolz/Poolz-Back/issues/23 for a solution.
