### ISSUE TITLE
Bug UI doesn't prevent me from overflowing pool.

### ISSUE THREAD

**Issue by aamironov** [The-Poolz/Poolz-Back#135]
**Describe the bug**
I can put any value in "Amount to swap" field and even higher than pool size.

**To Reproduce**
1. Press "Join" on any pool
2. Enter amount bigger than pool size in "Amount to swap"
<img width="683" alt="Screen Shot 2021-01-11 at 10 45 33 PM" src="https://user-images.githubusercontent.com/16032708/104279498-40c1c880-545f-11eb-8656-7475c8a5f0d5.png">
3. Press "Swap"
4. You will see error in your wallet 
<img width="364" alt="Screen Shot 2021-01-11 at 10 46 18 PM" src="https://user-images.githubusercontent.com/16032708/104279474-37d0f700-545f-11eb-8925-bdc12234d15b.png">

**Expected behavior**
UI should check user's balance to avoid it.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox

**Additional context**

**Wallet address**
0xef6ee1eCe8664605493e69De51F490c096BeEAA7

**Comment by Lomet** [comment]
This is the main issue for join dialog: https://github.com/The-Poolz/Poolz-Back/issues/35

Thanks for the report.
