### ISSUE TITLE
Bug need to approve each time when interacts with the same pool

### ISSUE THREAD

**Issue by aamironov** [The-Poolz/Poolz-Back#137]
**Describe the bug**
I interacted with the same pool twice. First time with amount 20, second with amount 10. Each time required me to approve currency.

**To Reproduce**
1. Try to join Pool
2. Click on Enter amount 20
3. Click Swap
4. Approve currency
5. Reject swap
6. Join the same pool
7. Click on Enter amount 10
8. Click Swap

**Expected behavior**
One approve

**Screenshots**
TXNs:
https://rinkeby.etherscan.io/tx/0x1d73622cb064a1c8b9d0790ea7faf962ebae81e3691fba9aa35b58944e2c2b82
https://rinkeby.etherscan.io/tx/0x70e77a288f566eeb492ae58cd5c3c9219410d09173da1b8eba3f7ec196f669e8
https://rinkeby.etherscan.io/tx/0x5c54255887f670f0be545c72e28b9767248316ba52238635a161f3e2aa32eeaa

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Firefox
 - Version 84

**Additional context**

**Wallet address**
0xef6ee1eCe8664605493e69De51F490c096BeEAA7

**Comment by Lomet** [comment]
We are thinking to add "Approve max value"
until then, we approve only what we gonna use for the next action, not make sure the assets are safe.
