### ISSUE TITLE
Bug 'Join' button doesn't dissapear after time pass without page refresh

### ISSUE THREAD

**Issue by aamironov** [The-Poolz/Poolz-Back#138]
**Describe the bug**
Created pool with very short time limit. Time left changed from timer to "Time Passed" sign, but "Join" button is still there and can be pressed

**To Reproduce**
1. Create pool for 1 minute
2. Wait 1 minutes

**Expected behavior**
"Join" -> "Locked"

**Screenshots**
<img width="1041" alt="Screen Shot 2021-01-11 at 11 33 34 PM" src="https://user-images.githubusercontent.com/16032708/104283790-ebd58080-5465-11eb-9e83-c04286f43676.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Firefox
 - Version 84

**Additional context**

**Wallet address**
0xef6ee1eCe8664605493e69De51F490c096BeEAA7

**Comment by Lomet** [comment]
Thanks for the report. the first issue for that: https://github.com/The-Poolz/Poolz-Back/issues/84
