### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Josan18** [The-Poolz/Poolz-Back#14]
**Describe the bug**
I tried to enter to the webpage but the site is constantly telling me that it is not secure and I can not enter

**To Reproduce**
Click on: https://app.poolz.finance/ and see the failure. There is an error with the security certificate

**Expected behavior**
It should be possible to enter to the website in order to follow the steps of the medium article and test the platform

**Screenshots**
![2](https://user-images.githubusercontent.com/77059284/103774879-8f213280-502d-11eb-86b4-f08adbba6fdb.PNG)
![WhatsApp Image 2021-01-06 at 14 44 33](https://user-images.githubusercontent.com/77059284/103775065-d4456480-502d-11eb-9743-659ebb4bc5c8.jpeg)

**Desktop (please complete the following information):**
I have received this message in Chrome and Safari
 - OS: iOS
 - Browser: safari
 - Version 14.2

 - OS: Windows
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)
 
**Wallet address**
0xE8750FC05F45E80E22Be835De3E609e0CadCa256

**Comment by Lomet** [comment]
Can you see what certificate you got there? like this
![image](https://user-images.githubusercontent.com/48094744/103777546-b7af2980-5039-11eb-983b-5405558d70cc.png)

**Comment by Lomet** [comment]
its looks like a local problem. no other users report it.
Advice: check the device for viruses.
