### ISSUE TITLE
Dashboard UI/UX Realignment

### ISSUE THREAD

**Issue by blackchained** [The-Poolz/Poolz-Back#140]
**Is your feature request related to a problem? Please describe.**
The current UI and UX of the dashboard needs improvements to make it more professional looking and better user experience.

**Describe the solution you'd like**
I think it needs more realignment in terms of elements position to clearly set hierarchy and make it simple and a lot cleaner. Here's my (small) realignment for now
![POOLZ r2](https://user-images.githubusercontent.com/71936911/104331605-3b7d8000-552a-11eb-9615-99d03bc93241.png)

**Describe alternatives you've considered**
It just needs improvements to look a lot better.

**Additional context**
In the above image

**Wallet address**
0x95a54A149f1437B4e7579E3b5dDF2bB62400f563

**Comment by Lomet** [comment]
Thank you for your input on this feature request. After reviewing the current state of this repository, we’ve decided that it is no longer actively maintained and can be archived.

This issue and others will now be closed as part of this archival process. If you have further feedback or need assistance, please reach out through our active channels or repositories.

Thank you for your contributions!
