### ISSUE TITLE
Investors can take advantage of the pool rewards by holding only 0.000001 POOLZ token

### ISSUE THREAD

**Issue by crypto-x-soldier** [The-Poolz/Poolz-Back#141]
**Describe the bug**
A pool is created with additional token rewards for the POOLZ token holders and this runs for the first 10% of the total time. In that space an investor can take advantage of this additional reward by just holding 0.000001 POOLZ tokens(taken 6 precision). This is an unfair advantage over the POOLZ holders who hold it in abundant.

**To Reproduce**
1. Go to 'https://app.poolz.finance/dashboard'
2. Click on 'Etherium' and click Connect.
3. As a Pool Owner, create a Pool with 'TEST' token with the swap ratio as 1ETH = 0.5 TEST for normal users and 1ETH = 0.7 TEST for POOLZ holders
4. Switch the wallet as a Investor of the pool. Make sure for this investor wallet has only 0.000001 the POOLZ token.
4. Join the pool and the investor will be able to successfully get total 0.7 TEST token 

**Expected behavior**
 Looks like the logic is set to check just whether the POOLZ token is greater than 0 for an investor in the pool. Ideally the minimum amount should set with a reasonable quantity. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Vivaldi
 - Version : 3.5

**Wallet address**
0xdD5F5feE4Db473ACa5A0b52EE459Abd35D098BEE

**Comment by Lomet** [comment]
> The pool is only for POOLZ holders. Wait until it is public or buy POOLZ to start investing (0.00008 is enough for testnet).
(it's more zeros actually)
We want that all can tey to $POOLZ benefit on test net.

thanks for the report.
