### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by enkidumeme** [The-Poolz/Poolz-Back#143]
**Describe the bug**
Checking the pool creator's address should open etherscan a new tab which it doesn't. When "going back" in the browser it goes back to the dashboard rather than back to the pool and disconnects the wallet.
**To Reproduce** rather than back to the pool
Join any pool and confirm. Then click on "Creator's Address". 

**Expected behavior**
Open etherscan in a new tab.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 84.0.2

**Additional context**

**Wallet address**
ERC20 wallet for POZ rewards
0xFCB33fbe33e1f0f066b41c24D91E994D8fd8e526

**Comment by Lomet** [comment]
Thanks for the report, you right, 
here is the first time: https://github.com/The-Poolz/Poolz-Back/issues/44
