### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by danielp1992** [The-Poolz/Poolz-Back#144]
**Cannot buy test via Metamask ios**
I can join the testpool (ID: 128) via metamask on iphone (ios), but i cannot fill in the amount I want to swap.

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard on iOS metamask.
2. Click on “join” of Pool ID: 128 (Poolz Finance)
3. Scroll down “i understand’ and check and click on “continue”.
4. See error (on the transaction page i cannot scroll down to fill in the amount i want to swap).

**Expected behavior**
The ability that i can scroll down in the transaction page to fill in the amount i want to swap. This is unfortunately not possible on the metamask ios.

**Screenshots**
![EBC6F66C-7F1A-460F-8D1C-D68A410CAEA4](https://user-images.githubusercontent.com/72663221/104452468-58a26500-55a3-11eb-836a-9d20a22e39f0.png)

**Desktop (please complete the following information):**
 - OS: iOS

**Additional context**
Since there is many active scams going on with metamask, especially via browser, it would be great to use metamask app instead of laptop/pc to buy tokens.

**Wallet address**
0xd872edF64c31Bc3957637Ce2B5ad220d98Bea092

**Comment by Lomet** [comment]
The support for mobile will come in a later stage.
thanks for the report.
