### ISSUE TITLE
Disable "Join" button when you call RemoveToken function

### ISSUE THREAD

**Issue by karmataktsang** [The-Poolz/Poolz-Back#146]
**Is your feature request related to a problem? Please describe.**
If there is a problem with the token you will call RemoveToken. But for now users can still buy the problem token without warning or denial.

**Describe the solution you'd like**
-Add line:
require(IsValidToken(_Token), "Need Valid ERC20 Token"); //check if _Token is ERC20
in **InvestETH** function
-Disable "Join" button

**Wallet address**
0xD76cEF7461aB4030F03A664A3bEB3cc3B824983D

**Comment by Lomet** [comment]
Nice idea. But not for now.
If we added a bad token? it's better to do It with a blacklist.
