### ISSUE TITLE
ALERT: Transaction Error. Exception thrown in contract code. Bug

### ISSUE THREAD

**Issue by iSkylark** [The-Poolz/Poolz-Back#149]
**Describe the bug**
I get an error in MetaMask when trying to exchange ETH for POOLZ: ALERT: Transaction Error. Exception thrown in contract code.

**To Reproduce**
1. Go to 'https://app.poolz.finance/dashboard'
2. Click on 'JOIN' on POOL 203, 202 or 200.
3. Enter 0.1 ETH to swap for POOLZ
4. See error in MetaMask window.

**Expected behavior**

**Screenshots**
<img width="252" alt="metamask error" src="https://user-images.githubusercontent.com/77087043/104714823-a4e6d400-5760-11eb-9791-d8e7c32e872f.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87

**Additional context**

**Wallet address**
0xDbB341a08b9bB63C54F73EE116BB5DE44861bf7A

**Comment by Lomet** [comment]
you can send the transaction, then we see the error on the ether scan.
(for me no error)

**Comment by iSkylark** [comment]
Yes, transaction went through, yet MetaMask throws an error "Exception Thrown in contract code" - which means there is something wrong with the contract code or in the least - exceptions are not handled properly - otherwise MetaMask wouldn't show error. Fixing that minor/text bug is up to you, I am just reporting it. :)

**Comment by Lomet** [comment]
Can you please link the TX?
we got a message on every revert - but it's not shown in Metamask - only in Etherscan
