### ISSUE TITLE
Pool Creation Bug

### ISSUE THREAD

**Issue by cryptoloverRobiul** [The-Poolz/Poolz-Back#15]
**Describe the bug**
Pool creation not working properly

**To Reproduce**
1. Go to 'Creat Pool and submitting token information'
2. Click on 'Set Swipe ratio then Swap rules info inputted and confirmed then clicking create pool'
3. See error: Pool creation failed

**Expected behavior**
It should see Pool creation successful

**Screenshots**
https://i.ibb.co/p3bywGN/Capture2.png

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [87.0.4280.88  (64-bit)]

**Additional context**
None

**Wallet address**
ERC20 wallet: 0x612E86E40ac3E40a2C0D33808AEb2cc28251B61f

**Comment by Lomet** [comment]
Someone post this issue first, duplicate: https://github.com/The-Poolz/Poolz-Back/issues/11
