### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by abuzerasr** [The-Poolz/Poolz-Back#16]
**Describe the bug**
When i try to join pool it said "not enough pools"

It should join the pool

**Screenshots**
![image](https://user-images.githubusercontent.com/11823642/103777582-8be86f80-504a-11eb-8986-450f707b904c.png)

**Desktop (please complete the following information):**

 - Browser brave

**Wallet address**
ERC20 wallet for POZ rewards
0xA767E4c1365323C7A7823206a3e647B97380799C

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/12#issuecomment-755310222
