### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by hoseincrypto** [The-Poolz/Poolz-Back#18]
**Describe the bug**
Button text is hardly visible in popups on Join pool. 

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Join Pool'
3. Scroll down to '.Continue button'

**Expected behavior**
Text should be clearly visible to 

**Screenshots**
Unchecked checkbox not visible:
![poolz](https://user-images.githubusercontent.com/77062177/103780630-87658c00-5035-11eb-9086-8d31b9610b82.png)

![Screenshot at Jan 06 15-01-12](https://user-images.githubusercontent.com/77062177/103779656-5b95d680-5034-11eb-9f69-afdd3fab68d7.png)
![ui2](https://user-images.githubusercontent.com/77062177/103780465-48373b00-5035-11eb-9ada-e70adbcdcc04.png)

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser Brave

**Additional context**

**Wallet address**
0x0954776ad6e37dCA1740DF6B24755cD91c4D0D22

**Comment by Lomet** [comment]
It looks like a local problem. thanks for the report.
