### ISSUE TITLE
Add a button Max quantity in Swap function

### ISSUE THREAD

**Issue by longboynd9** [The-Poolz/Poolz-Back#20]
Describe the bug
Cannot connect wallet automatic when refresh webpage again

To Reproduce

Go to 'https://app.poolz.finance/'
See error
Expected behavior
When My wallet has been connected. My wallet must be connect automatic when refresh webpage again

Screenshots
![image](https://user-images.githubusercontent.com/8565462/103781057-666a5e80-5068-11eb-86d6-fbad82f7e816.png)

Desktop (please complete the following information):

OS: Window 10
Browser: Google chorm
Version 85.0.4183.83
Additional context

Wallet address
0xc7db95F51C81C7A473b3E79cb5E0582FD8873a30

**Comment by Lomet** [comment]
It's a good idea, 
but if you swap all the ETH you will have no eth left for gas (to do more stuff with it).
on the new design - will be more options.

**Comment by longboynd9** [comment]
Yes. But many people know that after using uniswap a long time. If we have Max button, I will click Max and customize Eth quantity and click Swap. It's easy and fast when I must type quantity by hand.
