### ISSUE TITLE
First Reward, Bug

### ISSUE THREAD

**Issue by oguzutku1745** [The-Poolz/Poolz-Back#21]
**Describe the bug**
1-)After I created a pool, I couldn't enter the "My Investment" page. After I invested in pool, I refreshed the page then connected my wallet again. This time, I couldn't see the pool which I created. 

**To Reproduce**
1. Go to 'Create Pool, and follow the steps on "Test & Bug Bounty Program for Poolz v1.2 Platform is Now Live" on Medium to create a pool.'
2. Click on 'My Investment'
3. Click on 'Refresh Page'
4. Click on 'Connect Wallet'
5. Click on 'My Investment
6. Click on 'Created Pools'

**Expected behavior**
First, I expected to see My Investments. Second, I expected to see my pools

**Screenshots**
![Can'tSee](https://user-images.githubusercontent.com/76889160/103778664-9fdca300-5043-11eb-983e-d236c6d4d786.PNG)
![Can'tSee 2](https://user-images.githubusercontent.com/76889160/103778663-9fdca300-5043-11eb-8182-c46134e1b1a1.PNG)
![Can'tSee3](https://user-images.githubusercontent.com/76889160/103778666-a0753980-5043-11eb-9a7c-9caf11c55c59.PNG)
![Can'tSee4](https://user-images.githubusercontent.com/76889160/103778671-a0753980-5043-11eb-8479-209ca9059b2a.PNG)
![Can'tSee6](https://user-images.githubusercontent.com/76889160/103778672-a10dd000-5043-11eb-9b97-d187a4b87185.PNG)
After this screenshot, I thought that I couldn't create a pool first, after 5 or 10 mins, a pool appeared on 'Created Pools'. Then disappeared. Passed 20 minutes, I can't create a pool, I read the blog. Everything seems ok. I will add the link of my transactions, so that you can also examine them.
![Investments](https://user-images.githubusercontent.com/76889160/103778673-a10dd000-5043-11eb-8df8-1c73a8ccab0b.PNG)
![My Investment](https://user-images.githubusercontent.com/76889160/103778675-a1a66680-5043-11eb-875d-9a5e84c44bb0.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [Microsoft Egde]
 - Version [87.0.664.66]

**Additional context**
I created a pool and invested. I couldn't withdraw my funds now. Actually couldn't even find how will I do it. I will try it after 1 week.
Here is my transaction link. My TG: KyaTzu
https://rinkeby.etherscan.io/address/0x43ce28b996651b0b6f40d58f195f0fa8d5e19301

**Wallet address**
0x43Ce28b996651b0B6F40D58F195F0fA8d5E19301

**Comment by Lomet** [comment]
it's the same issue as here:  https://github.com/The-Poolz/Poolz-Back/issues/11
it's fixed now. you can try again.
