### ISSUE TITLE
Connection to ETH wallet is invisible after switching between Tomo and Moonbeam chains.

### ISSUE THREAD

**Issue by crypto-x-soldier** [The-Poolz/Poolz-Back#22]
**Describe the bug**
After connecting to metamask wallet my balance and ETH address is correctly displayed. Now then I switch the blockchain to Tomo and/or Moonbeam and when I return back to Etherium the connection details is invisible. 

**To Reproduce**
1. Go to 'https://app.poolz.finance/dashboard'
2. Click on 'Connect A Wallet'
3. Approve in Metamask.
4. Click 'TomoChain' in 'Choose a Chain' section
5. Click 'Etherium' in 'Choose a Chain' section

**Expected behavior**
Connection to ETH should be automatically visible even after switching between different blockchains. 

**Screenshots**
1. Before switching blockchain
![image](https://user-images.githubusercontent.com/77062578/103782020-f99d9700-505c-11eb-97b2-38b300dbb585.png)

2. After switching blockchain to Tomo and then back to Etherium
![image](https://user-images.githubusercontent.com/77062578/103782148-18039280-505d-11eb-8b74-bf68967bf699.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi

**Wallet address**
0xdD5F5feE4Db473ACa5A0b52EE459Abd35D098BEE

**Comment by Lomet** [comment]
for each chain need to change the wallet chain, then reconnect.
![image](https://user-images.githubusercontent.com/48094744/103791265-ed104300-504a-11eb-879c-0f1cfc52febf.png)
