### ISSUE TITLE
Cannot paste wallet address into "Token Contract Address" when dont have one character at least

### ISSUE THREAD

**Issue by longboynd9** [The-Poolz/Poolz-Back#23]
Cannot paste wallet address into "Token Contract Address" when dont have one character at least

Go to Create pool

Can paste wallet address into "Token Contract Address" although dont have one character at least

Screenshots
![image](https://user-images.githubusercontent.com/8565462/103782270-d2999200-5069-11eb-8e37-35830cd83a4a.png)

Desktop:
OS: Window 10
Browser: Google chorme
Version 85.0.4183.83

Wallet address
0xc7db95F51C81C7A473b3E79cb5E0582FD8873a30

**Comment by longboynd9** [comment]
After add 'a' character and Paste my wallet. And I cannot delete 'a'. After I put Backspace button. My cursor position is last character (at 'c' position). It is uncomfortable. You need to check careful this error.

**Comment by longboynd9** [comment]
After delete 'a0' character. I cannot put '0' character. Maybe cannot put '0' character at first position. This is wrong

**Comment by longboynd9** [comment]
Ah. I saw. I pasted contract of poolz, not be contract of POOLZ  token. But you need notify if it is not contract of token. 👍

**Comment by Lomet** [comment]
yes, but someone posted this before. thanks for the feedback 💯
