### ISSUE TITLE
My Investments : Bug Join

### ISSUE THREAD

**Issue by hoseincrypto** [The-Poolz/Poolz-Back#24]
**Describe the bug**
Join button do not work on my investments page. The pool is still not filled. Also opening a new tab disconnects wallet. 

**To Reproduce**
1. Go to '.My Investments'
2. Click on 'Join Button'

**Expected behavior**
The button should work If the pool is not full or it should not be there if user can not rejoin.

**Screenshots**
![Disconnect](https://user-images.githubusercontent.com/77062177/103783844-80d91380-5039-11eb-892e-291a71357f6e.gif)
![Disconnect2](https://user-images.githubusercontent.com/77062177/103783858-859dc780-5039-11eb-9f31-2ab9ca008c4e.gif)

**Desktop (please complete the following information):**
 - OS: Mojavi
 - Browser Brave
 - Version latest

**Additional context**

**Wallet address**
0x0954776ad6e37dCA1740DF6B24755cD91c4D0D22

**Comment by Lomet** [comment]
my investment will work only after the wallet connected (in the 2nd tab - it's not)
but yes - the join button need to work
