### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AR69AL** [The-Poolz/Poolz-Back#25]
**Describe the bug**
A clear and concise description of what the bug is. Reference photo. Text mismatch overlay on mobile. iOS IPHONE PRO 11 Metamask native browser. 
![84BC7F91-C756-4D19-93EA-DE68D6F96BC9](https://user-images.githubusercontent.com/75546850/103784287-c41a8e80-5007-11eb-999d-07ae1ba8ce4f.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Wallet address**
ERC20 wallet for POZ rewards

**Comment by Lomet** [comment]
The test right now is only for desktop - the mobile version will be at later stages.
thanks for the feedback.
