### ISSUE TITLE
Hyperlink for Twitter social button

### ISSUE THREAD

**Issue by minhthai58** [The-Poolz/Poolz-Back#27]
**Describe the bug**
Not optimized hyperlink for Twitter social button

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Scroll down to the bottom
3. Look at the left
4. Hover the mouse on Twitter icon

**Expected behavior**
https://twitter.com/Poolz__
Instead of: https://mobile.twitter.com/Poolz__

**Screenshots**
![image](https://user-images.githubusercontent.com/71914636/103785895-548bba00-506e-11eb-9265-fd229bbd3b02.png)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**
N/A

**Wallet address**
0x306B769A3B4B4c2D59fC1580f581796Ed9dfDf2F

**Comment by Lomet** [comment]
nice to note.
