### ISSUE TITLE
GUI Set trust ratio responsive is not good

### ISSUE THREAD

**Issue by longboynd9** [The-Poolz/Poolz-Back#28]
GUI Set trust ration responsive is not good
"Set trust ratio" button is on textinput 

Screenshots
image
![image](https://user-images.githubusercontent.com/8565462/103786317-e3003b80-506e-11eb-9e61-da2af4a495d7.png)

AND
![image](https://user-images.githubusercontent.com/8565462/103786720-543fee80-506f-11eb-9a4e-82d4ecebacc7.png)

Desktop:
OS: Window 10
Browser: Google chorme
Version 85.0.4183.83

Wallet address
0xc7db95F51C81C7A473b3E79cb5E0582FD8873a30

**Comment by Lomet** [comment]
We support at the moment only desktop resolution.
it will be fixed when mobile support added.
Thanks for the report.
