### ISSUE TITLE
I cannot delete number to type other number in quantity input

### ISSUE THREAD

**Issue by longboynd9** [The-Poolz/Poolz-Back#30]
I think you want to quantity is not zero (0). But this thing is uncomfotable to use.

Go to Lock Deal: https://app.poolz.finance/lockeddeal
Put contract token and click "Set Trust Ratio". 
![image](https://user-images.githubusercontent.com/8565462/103787412-2018fd80-5070-11eb-882d-3e708b80ab83.png)

In "2. Trust Rule".
If I type a number >0. I cannot delete to last number. 
Example: I put "5". Then I want to delete "5" and type "2". But I cannot delete "5".  So it is uncomfotable.
![image](https://user-images.githubusercontent.com/8565462/103787714-843bc180-5070-11eb-9c8a-ead8e1529261.png)

Desktop:
OS: Window 10
Browser: Google chorme
Version 85.0.4183.83

Wallet address
0xc7db95F51C81C7A473b3E79cb5E0582FD8873a30

**Comment by Lomet** [comment]
Thanks for the report, Lock Deal is not part of the current test but we will keep this in mind.
