### ISSUE TITLE
Small Bug - informational

### ISSUE THREAD

**Issue by llllllffffff** [The-Poolz/Poolz-Back#31]
**Describe the bug**
When creating a locked pool, there was small time delay inside transaction confirmation. The problem was, that it was already showing 'Create a pool', which seemed strange.

**To Reproduce**
1. 'Add locked deal'
2. Put in info for TEST token
3. Submit Transaction after setting 'Trust Rules'
4. This screen on Step 3 of creating a 'Locked deal'

**Expected behavior**
It would be great if you could add a little loading sign or make clear that the pool cannot be created yet, since it is done on normal pools.

**Screenshots**

https://ibb.co/Qcw7b22

**Desktop (please complete the following information):**
Windows in Firefox 83

**Additional context**
/

**Wallet address**
0x204fa60289495f3942Acc42c34a51fbcFd59CB2e

Kind regards and keep up your great work!

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/30
