### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by llllllffffff** [The-Poolz/Poolz-Back#33]
**Describe the bug**
In 'My Investments' the 'button' is without function - it only 'blinks' - gets bigger and smaller

**To Reproduce**
1. Joining a pool
2. Go to 'My Poolz' > 'My Investments'
3. The join button on the right

**Expected behavior**
Joining the pool for more money

**Screenshots**
https://ibb.co/6RDYLYG

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 83

**Additional context**
/

**Wallet address**
0x204fa60289495f3942Acc42c34a51fbcFd59CB2e

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/24
