### ISSUE TITLE
Bug - My investment

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#37]
Describe the bug
Sometimes when entering the 'My Investments' page, you are left with a message saying 'Loading...' although it appears to be doing nothing. This appears to happen sometimes even when there are pools joined and invested.

To Reproduce
Click 'My investments' link on the left.

Expected behavior
Should show the results, or potentially a message saying 'You have no investments yet' if there are none to be displayed.

Screenshots
<img width="1440" alt="Screen Shot 2021-01-06 at 16 02 57" src="https://user-images.githubusercontent.com/39380100/103791246-23919200-503a-11eb-899b-595201a7475f.png">

Desktop (please complete the following information):

MacOS 10.12.6
Chrome
87.0.4280.88 (Official Build) (x86_64)
Additional context
Wallet Connected via Metamask on Rinkeby.

Wallet address
0xD4E5e3e9f936a59568C3A7c6159c5cFCE328D496

**Comment by Lomet** [comment]
> Should show the results, or potentially a message saying 'You have no investments yet' if there are none to be displayed.

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/24
