### ISSUE TITLE
Bug - zero locked tokens

### ISSUE THREAD

**Issue by llllllffffff** [The-Poolz/Poolz-Back#38]
**Describe the bug**
I am able to lock 0, "zero" tokens in a pool and fully create that pool.

**To Reproduce**
1. Go to 'Create Pool'
2. Set any token address > continue
3. Fill out 'Swap Rules' - **leave 'amount of tokens to be locked empty**
4. confirm both transactions afterwards

**Expected behavior**
probably error message

**Screenshots**
https://ibb.co/pXsxVt7
https://ibb.co/68yfKpy

**Desktop (please complete the following information):**
 - Windows
 - Firefox
 - Version 83

**Additional context**
/

**Wallet address**
0x204fa60289495f3942Acc42c34a51fbcFd59CB2e

**Comment by Lomet** [comment]
this is a nice one - we will look into it,
thanks for the report

**Comment by Lomet** [comment]
will be fixed in both,
UI and Contract

**Comment by omryoz** [comment]
Fixed in UI
