### ISSUE TITLE
Bug: Confusing Flow after Finishing Token Swap

### ISSUE THREAD

**Issue by minhthai58** [The-Poolz/Poolz-Back#39]
**Describe the bug**
After Join Pool and Swap, there is no way to check the token received. When I clicked My Investments, a Pool No.30 (which does not exist yet) appears, the Join Button is even not clickable. 

**To Reproduce**
1. After finishing Swap Token and Confirm on MetaMask
2. Click on My Pools on the left of the Dashboard
3. Click on My Investments
4. See the Pool No.30
5. Click the Join Button

**Expected behavior**
Disable the button. Pool No.30 did not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/71914636/103789830-062cea00-5073-11eb-8494-24894bf7d2a1.png)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**
N/A

**Wallet address**
0x306B769A3B4B4c2D59fC1580f581796Ed9dfDf2F

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/24
