### ISSUE TITLE
Visual Bug - Bad accessibility

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#41]
**Describe the bug**
'Swap' CTA button isn't visible on some platforms.

**To Reproduce**
1. Join any pool
2. Accept T&Cs and continue.
3. Scroll to bottom

**Expected behavior**
The button should be easily visible.

**Screenshots**
<img width="742" alt="Screen Shot 2021-01-06 at 16 08 36" src="https://user-images.githubusercontent.com/39380100/103790917-b67dfc80-5039-11eb-9313-fa1a94fd6abf.png">

**Desktop (please complete the following information):**
 - MacOS 10.12.6
 - Chrome
 - 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Wallet Connected via Metamask on Rinkeby.

**Wallet address**
0x1C69ac5509e5fac81e1636f03F9AAa3EB56CdbE6

**Comment by Lomet** [comment]
Thanks for the report
https://github.com/The-Poolz/Poolz-Back/issues/18
