### ISSUE TITLE
Very Small Bug

### ISSUE THREAD

**Issue by llllllffffff** [The-Poolz/Poolz-Back#42]
**Describe the bug**
When joining any pool where I hava a zero-balance, the following pop-up shows to buy $POOLZ, disregarding the initial token of the pool

**To Reproduce**
1. Go to 'Dashboard'
2. Click join on any pool, where I hava a zero balance

**Expected behavior**
Tell me to buy the exact token used in the pool

**Screenshots**
https://ibb.co/YkPwZ2c
https://ibb.co/PWcLn0Z

**Desktop (please complete the following information):**
 - Windows 10
 - FireFox
 - Version 83

**Additional context**
/

**Wallet address**
0x204fa60289495f3942Acc42c34a51fbcFd59CB2e

**Comment by Lomet** [comment]
If I understand correctly, the pool you trying to join is for $poolz holders only, and you have not enough $poolz.

> The pool is only for POOLZ holders. Wait until it is public or buy POOLZ to start investing (0.00008 is enough for testnet).
