### ISSUE TITLE
Bug: Search Bar did not work with Token Contract Address

### ISSUE THREAD

**Issue by minhthai58** [The-Poolz/Poolz-Back#43]
**Describe the bug**
When I searched the token contract address of TestToken (0xe606c5CF639628Ae69F391aeA32eE3D347De86A8), nothing shows up while there are still many pools of TestToken

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on Search Bar
3. Type: 0xe606c5CF639628Ae69F391aeA32eE3D347De86A8
4. See the screen: No Pools to show

**Expected behavior**
All pools of TestToken should appear in the search result

**Screenshots**
![image](https://user-images.githubusercontent.com/71914636/103791509-1ba31380-5075-11eb-8246-e3df88fd7e01.png)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**
N/A

**Wallet address**
0x306B769A3B4B4c2D59fC1580f581796Ed9dfDf2F

**Comment by Lomet** [comment]
Thanks for the report, 
https://github.com/The-Poolz/Poolz-Back/issues/34
