### ISSUE TITLE
Rows per page to be implemented in Dashboard Pools

### ISSUE THREAD

**Issue by crypto-x-soldier** [The-Poolz/Poolz-Back#45]
**Is your feature request related to a problem? Please describe.**
Currently there are no pagination implemented to display the poolz in the dashboard. A limit should be setup to display number of rows(poolz) to display so that the page loads quickly.

**Describe the solution you'd like**
'Rows per page:' to be implemented in the Dashboard page to display pools similar like available in 'Locked Deals' section.

**Describe alternatives you've considered**
NA

**Additional context**

Same like this feature to be implemented in Dashboard

![image](https://user-images.githubusercontent.com/77062578/103791935-0fb15480-5069-11eb-9078-f6810332500d.png)

**Wallet address**
0xdD5F5feE4Db473ACa5A0b52EE459Abd35D098BEE

**Comment by Lomet** [comment]
thanks for the report, this is a scale issue for later stages.
