### ISSUE TITLE
Bug: Search Bar did not work with Pool Name

### ISSUE THREAD

**Issue by minhthai58** [The-Poolz/Poolz-Back#47]
**Describe the bug**
When I searched the name of pools: TestToken, nothing shows up while there are still many pools of TestToken

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on Search Bar
3. Type: TestToken
4. See the screen: No Pools to show

**Expected behavior**
All pools which have the name TestToken should appear in the search result

**Screenshots**
![image](https://user-images.githubusercontent.com/71914636/103792377-24e0b000-5076-11eb-80b3-3b9ee16e9dbd.png)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**
N/A

**Wallet address**
0x306B769A3B4B4c2D59fC1580f581796Ed9dfDf2F

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/34
