### ISSUE TITLE
Update the Error Message in My Investments section

### ISSUE THREAD

**Issue by crypto-x-soldier** [The-Poolz/Poolz-Back#48]
**Describe the bug**
Currently if there is no investment made by the user then the message shows as 'Loading...'. 

**To Reproduce**
1. Go to 'https://app.poolz.finance/dashboard'
2. Click on 'Connect Wallet'
3. Select 'My Pools -> My Investments'

**Expected behavior**
A message like 'No Investments to Show'

**Screenshots**

![image](https://user-images.githubusercontent.com/77062578/103793773-1ee4d200-506a-11eb-8ed2-8a418569aa5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Vivaldi
 - Version : 3.5

**Additional context**

**Wallet address**
0xdD5F5feE4Db473ACa5A0b52EE459Abd35D098BEE

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/24
