### ISSUE TITLE
Visual Bug in pools

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#49]
**Describe the bug**
Font sizes appear to be different on pool entry pages. For example, Token Cap is a different size to Time Left, as is the text on the right of each of those sections. It feels like there should be some consistency.
 
**To Reproduce**
1. Join any pool
2. Agree and continue

**Expected behavior**
There should be some consistency in font sizes.

**Screenshots**
<img width="744" alt="Screen Shot 2021-01-06 at 16 37 34" src="https://user-images.githubusercontent.com/39380100/103795320-bc75dc80-503d-11eb-812f-80cb04345558.png">

**Desktop (please complete the following information):**
- MacOS 10.12.6
- Chrome
- 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Connected via MetaMask using Rinkeby

**Wallet address**
0x1C69ac5509e5fac81e1636f03F9AAa3EB56CdbE6

**Comment by Lomet** [comment]
Thanks for the report, this will be fixed with a new design.
