### ISSUE TITLE
Bug: Confusing Toggle DSP / TLP

### ISSUE THREAD

**Issue by minhthai58** [The-Poolz/Poolz-Back#51]
**Describe the bug**
It is confusing when using the toggle to choose between DSP or TLP during the stage of creating a pool.

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on “Create Pool.”
3. Create Your Pool interface appears
4. Click on Step No.2
5. Scroll down to see Rules: DSP / TLP

**Expected behavior**
The Toggle should be clear which is DSP, TLP. For example: DSP on the left of the toggle, TLP on the right of the toggle

**Screenshots**
![image](https://user-images.githubusercontent.com/71914636/103796028-4d1dde00-5079-11eb-93a8-d3a39547f565.png)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**
N/A

**Wallet address**
0x306B769A3B4B4c2D59fC1580f581796Ed9dfDf2F

**Comment by Lomet** [comment]
This will be fixed with a new design. thanks for the report.
