### ISSUE TITLE
UX inconsistency

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#53]
**Describe the bug**
When creating a new pool, the link at the bottom says 'Set Trust Ratio', but the 2nd section is named '2. Trust Rules' - it feels inconsistent, shouldn't these match, as they do when you go to click 'confirm' on the next page.

**To Reproduce**
1. Create a Pool
2. See link underneath

**Expected behavior**
Should be consistent naming / CTA labelling

**Screenshots**
<img width="728" alt="Screen Shot 2021-01-06 at 16 48 59" src="https://user-images.githubusercontent.com/39380100/103796690-715cc900-503f-11eb-8cd5-4143b8168556.png">

**Desktop (please complete the following information):**
 - MacOS 10.12.6
 - Chrome
 - 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Wallet Connected via MetaMask on Rinkeby

**Wallet address**
0x1C69ac5509e5fac81e1636f03F9AAa3EB56CdbE6

**Comment by Lomet** [comment]
This will be fixed with the new design. thanks for the report.
