### ISSUE TITLE
Visual enhancements

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#54]
**Describe the bug**
When wallet is connected, you can't really see this. Perhaps it should be green or bolder/brighter in the top right. 

**To Reproduce**
1. Connect wallet
2. Look at top right of main page.

**Expected behavior**
It should be more easily visible.

**Screenshots**
<img width="1440" alt="Screen Shot 2021-01-06 at 16 54 59" src="https://user-images.githubusercontent.com/39380100/103797236-1bd4ec00-5040-11eb-959e-8ab4b298810c.png">

**Desktop (please complete the following information):**
 - MacOS 10.12.6
 - Chrome
 - 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Wallet Connected via MetaMask on Rinkeby

**Wallet address**
0x1C69ac5509e5fac81e1636f03F9AAa3EB56CdbE6

**Comment by Lomet** [comment]
Thanks for the report, we will take this into consideration on the new design.
