### ISSUE TITLE
Language Improvements

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#57]
**Describe the bug**
The message when trying to join a pool without enough Poolz contains bad grammar and is not a good use of English

**To Reproduce**
1. Join a poolz pool
2. Try to join.

**Expected behavior**
The message should be in a better tone of voice and correct grammar.

**Screenshots**
<img width="875" alt="Screen Shot 2021-01-06 at 17 05 36" src="https://user-images.githubusercontent.com/39380100/103798516-bda90880-5041-11eb-81c8-f309bf97488a.png">

**Desktop (please complete the following information):**
 - MacOS 10.12.6
 - Chrome
 - 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Wallet Connected via MetaMask on Rinkeby

**Wallet address**
0x1C69ac5509e5fac81e1636f03F9AAa3EB56CdbE6

**Comment by evdmx** [comment]
The line should read something like this - ** You currently don’t have any Poolz, buy Poolz below and start to invest! **

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/29
