### ISSUE TITLE
'Create Pool' button doesn't work after rejecting transaction in Metamask

### ISSUE THREAD

**Issue by crypto-x-soldier** [The-Poolz/Poolz-Back#58]
**Describe the bug**
When creating a locked pool, in the last step after I click 'Create Pool' the metamask opens up. I reject the transaction in Metamask, I am unable to again click 'Create Pool' button  to re-initiate the transaction as it does nothing.

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on 'Locked Deals'
3. Click 'Add Locked Deal' button
4.  In 'Token Information' Enter Token Contract Address  as 0x200944BB9427bBdcDB36d15A8e29CfF7083C03E7
5. Click 'Set Trust Ratio'
6. Enter amount as 500
7. Click Confirm
8. Click Reject in the Metamask.
9. Click Create Pool button to re-initiate the metamask approval. This is the place the button doesnt work.

**Expected behavior**
Until a pool is approved I should be able to Open Metamask approval multiple times when 'Create Pool' button is clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/77062578/103798684-0ecff100-5070-11eb-8683-e753431b54c9.png)

Desktop (please complete the following information):
 - OS: Windows 10
 - Browser : Vivaldi
 - Version : 3.5

**Wallet address**
0xdD5F5feE4Db473ACa5A0b52EE459Abd35D098BEE

**Comment by Lomet** [comment]
this test is not for the locked deal section, we will get to it later stage.
thanks for the report.

**Comment by crypto-x-soldier** [comment]
@Lomet This is happening for the regular new pool creation scenario as well..
