### ISSUE TITLE
No way of knowing which wallet is connected from on the dashboard

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#59]
**Describe the bug**
When the wallet is connected, it doesn't display which wallet. I use multiple ETH wallets and all sites running on ETH usually show which wallet is connected.

**To Reproduce**
1. Connect Wallet
2. Look at top right of page.

**Expected behavior**
The ETH address of connected wallet should be displayed, or at least the avatar for that link.

**Screenshots**
<img width="314" alt="Screen Shot 2021-01-06 at 17 10 16" src="https://user-images.githubusercontent.com/39380100/103798984-5b043c80-5042-11eb-9e04-03e65aaf01c2.png">

**Desktop (please complete the following information):**
 - MacOS 10.12.6
 - Chrome
 - 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Wallet Connected via MetaMask on Rinkeby

**Wallet address**
0x1C69ac5509e5fac81e1636f03F9AAa3EB56CdbE6

**Comment by evdmx** [comment]
This appears to only happen when on mobile, ipad or smaller resolution laptops.

**Comment by Lomet** [comment]
Good one, I'll mix it with this one: https://github.com/The-Poolz/Poolz-Back/issues/50

**Comment by Lomet** [comment]
It is:
![image](https://user-images.githubusercontent.com/48094744/104428587-533a2000-558d-11eb-8862-cfff965444dd.png)

**Comment by evdmx** [comment]
Unfortunately not visible when viewing on a small laptop or iPad
