### ISSUE TITLE
ETH balance and ETH address are not seen on dashboard.

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#61]
**Describe the bug**
When viewing on some smaller resolutions, ETH balance and ETH address are not seen on dashboard.

**To Reproduce**
1. View on smaller resolution screens.

**Expected behavior**
ETH Balance and ETH Address are not visible.

**Screenshots**
<img width="1268" alt="Screen Shot 2021-01-06 at 17 22 10" src="https://user-images.githubusercontent.com/39380100/103800154-f34ef100-5043-11eb-8ea3-f2e3f2de8121.png">

<img width="1440" alt="Screen Shot 2021-01-06 at 17 22 18" src="https://user-images.githubusercontent.com/39380100/103800166-f6e27800-5043-11eb-81ed-ec6007321366.png">

**Desktop (please complete the following information):**
 - MacOS 10.12.6
 - Chrome
 - 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Wallet Connected via MetaMask on Rinkeby

**Wallet address**
0x1C69ac5509e5fac81e1636f03F9AAa3EB56CdbE6

**Comment by Lomet** [comment]
we currently not supporting mobile (low resolution) devices.
when we add it, with the new design - it will work well.
