### ISSUE TITLE
Bug: List of Created Pools is not correct

### ISSUE THREAD

**Issue by minhthai58** [The-Poolz/Poolz-Back#63]
**Describe the bug**
When I checked my Created Pools, the list also includes other pools which do not belong to me.

**To Reproduce**
1. Go to https://app.poolz.finance/dashboard
2. Click on Create Pool
3. Finish all steps of Creating Pool
4. Click on My Pools - Created Pools
5. See the list.

**Expected behavior**
Only show my Created pools (No.16), not other ones (No.17)

**Screenshots**
![image](https://user-images.githubusercontent.com/71914636/103800600-2e224a80-507f-11eb-9a1b-35020727d16e.png)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**
N/A

**Wallet address**
0x306B769A3B4B4c2D59fC1580f581796Ed9dfDf2F

**Comment by Lomet** [comment]
Can you make this bug appear again?
I have a suspicion that it happened when the new pool created gets inside my pool list.
We need more information to catch this bug.
Thanks for the report.

**Comment by Lomet** [comment]
It's fixed:
When "my pools" were open and someone adds a new pool, it added to the wrong list.

Thanks for the report.
