### ISSUE TITLE
Values remain regardless of pool

### ISSUE THREAD

**Issue by evdmx** [The-Poolz/Poolz-Back#64]
**Describe the bug**
When typing a value in the pool screen then returning to the dashboard, the values entered before remain each time you enter the pool.. regardless of which pool you choose to join.

**To Reproduce**
1. Join a public pool
2. Enter values
3. Exit pool
4. Join a different public pool

**Expected behavior**
Values should be scrapped from one pool to another, when you exit. It seems like a bug, the values should return to zero when entering a new pool, to avoid mistakes and chances for user error.

**Screenshots**
https://user-images.githubusercontent.com/39380100/103800966-f8607000-5044-11eb-9050-fa3d08b3c254.mov

**Desktop (please complete the following information):**
 - MacOS 10.12.6
 - Chrome
 - 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Wallet Connected via MetaMask on Rinkeby

**Wallet address**
0xD4E5e3e9f936a59568C3A7c6159c5cFCE328D496

**Comment by Lomet** [comment]
This is an issue. The fix will be in this one : https://github.com/The-Poolz/Poolz-Back/issues/35

**Comment by Lomet** [comment]
https://github.com/The-Poolz/Poolz-Back/issues/24

**Comment by omryoz** [comment]
fixed on "5adeecd"
--
