### ISSUE TITLE
BUG in search tool

### ISSUE THREAD

**Issue by dhruvp2018** [The-Poolz/Poolz-Back#65]
whenever we use search tool ,we cant get proper search. You will understand by screenshot. when we search by pool name or id then we cant get the response which should we get.

![photo6318971467919895189](https://user-images.githubusercontent.com/36085227/103801767-34f79000-5074-11eb-9842-7c18cd82880c.jpg)
![photo6318971467919895188](https://user-images.githubusercontent.com/36085227/103801775-36c15380-5074-11eb-8ed9-32a585f2a94a.jpg)
![photo6318971467919895187](https://user-images.githubusercontent.com/36085227/103801776-36c15380-5074-11eb-95dd-6bd19ddf0f49.jpg)
![photo6318971467919895186](https://user-images.githubusercontent.com/36085227/103801777-3759ea00-5074-11eb-8552-38969024606b.jpg)
![photo6318971467919895185](https://user-images.githubusercontent.com/36085227/103801780-3759ea00-5074-11eb-8228-ab48aba1288d.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]   windows 10
 - Browser [e.g. chrome, safari]  chrome 

**Wallet address**
0x8076E5e5802570fBC57EAB4F7a26A78AA971E1D4

**Comment by Lomet** [comment]
Thanks for the information. the first issue is here: https://github.com/The-Poolz/Poolz-Back/issues/34
