### ISSUE TITLE
on dashboard we can see pools only after connecting wallet

### ISSUE THREAD

**Issue by dhruvp2018** [The-Poolz/Poolz-Back#66]
**Describe the bug**
when we visit dashboard , we cant see all pools before connecting our wallet.

**To Reproduce**
1. Go to "https://app.poolz.finance/dashboard"
2. Connect wallet

**Expected behavior**
when we visit "https://app.poolz.finance/dashboard" , we must see all the pools regardless connecting wallet.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser= chrome
 

**Additional context**

**Wallet address**
0x8076E5e5802570fBC57EAB4F7a26A78AA971E1D4
![photo6318971467919895191](https://user-images.githubusercontent.com/36085227/103803127-2ad69100-5076-11eb-9d22-dc891b4352e0.jpg)

**Comment by Lomet** [comment]
Can you remake this problem?
It may be from "lag" to the network.
I'll keep it open for - let's see if its returns.

**Comment by Lomet** [comment]
it's confirmed.
the problem comes from infura limits.

Thanks for the report.
