### ISSUE TITLE
when we refresh the page ,each time ,we have to connect wallet, its Irritating 

### ISSUE THREAD

**Issue by dhruvp2018** [The-Poolz/Poolz-Back#70]
**Is your feature request related to a problem? Please describe.**
when we refresh the page ,each time ,we have to connect wallet, its Irritating . 

**Describe the solution you'd like**
its must be connected.

**Wallet address**
0x8076E5e5802570fBC57EAB4F7a26A78AA971E1D4

**Comment by Lomet** [comment]
Thanks for that. let's keep the discussion about it here: https://github.com/The-Poolz/Poolz-Back/issues/19
