### ISSUE TITLE
Solidity's transfer() should no longer be used

### ISSUE THREAD

**Issue by pauliax** [The-Poolz/Poolz-Back#74]
**Describe the bug**
After the Istanbul hard fork, it is no longer safe to use  .transfer() function to send ether. It forwards only 2300 gas and if the receiver is not a wallet but a contract with a custom fallback function, then this call will fail. This is what unfortunately happened to betfi launchpad contract and now these >1000 ETH are stuck in the contract forever: https://etherscan.io/address/0xa205d797243126f312ae63bb0a5ea9a32fb14f41#code

More info: https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/

https://github.com/The-Poolz/Poolz-Back/blob/e895a7376ce31458b5df4c1584dc9eca8b464ccd/contracts/Invest.sol#L61

https://github.com/The-Poolz/Poolz-Back/blob/e895a7376ce31458b5df4c1584dc9eca8b464ccd/contracts/ETHHelper.sol#L45-L48

Here is the suggested way to solve it:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/9daa0d4d2fadc594d6756a83648c80007276ac04/contracts/utils/Address.sol#L53-L59

**Wallet address**
_0x523B5b2Cc58A818667C22c862930B141f85d49DD_

**Comment by Lomet** [comment]
```
    function TransferETH(address _Reciver, uint256 _ammount) internal {
        emit TransferOutETH(_ammount, _Reciver);
        uint256 beforeBalance = address(_Reciver).balance;
        _Reciver.transfer(_ammount);
        require(SafeMath.add(beforeBalance,_ammount)==address(_Reciver).balance, "The transfer did not complite");
    }
```
