### ISSUE TITLE
Code Bug

### ISSUE THREAD

**Issue by ttakumat** [The-Poolz/Poolz-Back#75]
**Describe the bug**
At contract/ThePoolz.sol code has misspelling at line 49 & 51.

**To Reproduce**
1. Go to contracts/ThePoolz.sol.
(https://github.com/The-Poolz/Poolz-Back/blob/main/contracts/ThePoolz.sol)
2. See line 49 and 51.
3. Function Safework has misspelling. 

**Expected behavior**
“then” should be “than”

**Screenshots**
![99953A09-A3C1-44BA-92A9-DE5CA02092C0](https://user-images.githubusercontent.com/50645218/103807898-76029b00-509a-11eb-8a55-6a070c1a98f3.jpeg)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser safari
 - Version ?

**Additional context**
NA

**Wallet address**
0x50Eb12BF8911f792F41b94C60584c30372661dF1

**Comment by Lomet** [comment]
```
    //will revert if less than parameters
    function SafeWork() external returns (uint256, uint256) {
        require(CanWork(), "Need more than minimal work count");
        return DoWork();
    }
```
