### ISSUE TITLE
Wallet balance bar on top

### ISSUE THREAD

**Issue by rjramesh** [The-Poolz/Poolz-Back#76]
Feature request:

Problem: 
I don't show our main portfolio or multiple assets we needed?

Solution :

On home page I don't see our balance i need to go on explorer to find our balance .
We need show our wallet balance of poolz or multiple asset see on top bar. 

Screenshot:

https://ibb.co/2ZgmmC6

**Wallet address**
ERC20 wallet for POZ rewards
0x02B860783d1957F9DC0870185B8Bf7714eED9604

**Comment by Lomet** [comment]
We can talk about it here:

https://github.com/The-Poolz/Poolz-Back/issues/50
