### ISSUE TITLE
WithdrawERC20Fee does not check if transfer was successful

### ISSUE THREAD

**Issue by pauliax** [The-Poolz/Poolz-Back#79]
**Describe the bug**
The code does not check if the token transfer was successful:

https://github.com/The-Poolz/Poolz-Back/blob/e895a7376ce31458b5df4c1584dc9eca8b464ccd/contracts/Manageable.sol#L84-L87

Some tokens do not revert on failure, but instead return false, for example, ZRX: https://etherscan.io/address/0xa205d797243126f312ae63bb0a5ea9a32fb14f41#code

In such a case FeeMap will be set to 0 anyway and the value will be lost forever.

Potential solution: use OpenZeppelin's SafeERC20: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol

**Wallet address**
_0x523B5b2Cc58A818667C22c862930B141f85d49DD_

**Comment by Lomet** [comment]
That is very interesting.
But we got a filter on MainCoin (this is the only way to get the fee)
we will think about it.

**Comment by Lomet** [comment]
```
    function WithdrawERC20Fee(address _Token, address _to) public onlyOwner {
        uint256 temp = FeeMap[_Token];
        FeeMap[_Token] = 0;
        TransferToken(_Token, _to, temp);
    }
```
