### ISSUE TITLE
2 bugs to test 

### ISSUE THREAD

**Issue by kveykva** [The-Poolz/Poolz-Back#82]
BUG #1
Description : Requesting Ether from the faucet ( https://www.rinkeby.io/#faucet) doesn't work. I see my etherwallet added to the list of wallets but I didn't receive anything.

To reproduce : 
1. Go to twitter and create a tweet including your ether wallet address.
2. Paste the tweet link in the Rinkeby Authenticated Faucet and request any amount of ether.
3. Check your etherwallet with Metamask and notice on the Rinkeby Test Network that you received no ETH, with no option to ask for more ETH until the next allowance period.

Expected behaviour : 
Some ETH was supposed to be received in my wallet on the Rinkeby Test Network.

![No ETH to test](https://user-images.githubusercontent.com/77078084/103822040-5f7a2680-503d-11eb-9bef-71736879b7ae.png)

![No option to ask for more ETH to test](https://user-images.githubusercontent.com/77078084/103822043-6143ea00-503d-11eb-9168-1bddf4718299.png)

Desktop:
- Windows 10 Home
- Chrome
- Version 87.0.4280.88 (Official Build) (64-bit)

Wallet address : 
0xbad979702A09841A7672FB6E3C12c3368DFF2A19

------------------------------------------------------------------------------------------------------------------------------------------
Bug #2 
Description : Pressing Join on the Test token pool ID 18 causes the page to become completely go blank with no option to go back to the previous page.

To reproduce : 
1. Go to the https://app.poolz.finance/dashboard page and connect your ether wallet while making sure you have the Kinkeby Test Network selected in your wallet
2. Press the green button on the TestToken pool with 18 as the ID.
3. Notice completely blank page.

Expected behaviour : 
A message with a warning should pop up and ask for confirmation.

![Blank page poolz](https://user-images.githubusercontent.com/77078084/103822026-5ab57280-503d-11eb-86b3-0ba78a26ca8f.png)

Desktop:
- Windows 10 Home
- Chrome
- Version 87.0.4280.88 (Official Build) (64-bit)

Wallet address : 
0xbad979702A09841A7672FB6E3C12c3368DFF2A19

**Comment by Lomet** [comment]
The first problem is the Rinkeby bug, its looks like it fixed now.
The second part, it's a true bug, will be fixed soon,
Thanks for the report.
