### ISSUE TITLE
Bug : Js error in console

### ISSUE THREAD

**Issue by hoseincrypto** [The-Poolz/Poolz-Back#85]
**Describe the bug**
There is a Js error in console. 

**To Reproduce**
1. Go to 'any page'
2. Open Browser console, there is a Js error

**Expected behavior**
Check Js error in Console

**Screenshots**
![poolz-js-console](https://user-images.githubusercontent.com/77062177/103833524-82c6c500-5081-11eb-9903-9ad1da7db23c.png)

**Desktop (please complete the following information):**
 - OS: MacOs Mojave
 - Browser  chrome, Firefox, Brave
 - Version 

**Additional context**

**Wallet address**
0x0954776ad6e37dCA1740DF6B24755cD91c4D0D22

**Comment by llllllffffff** [comment]
also on Windows 10 with Chrome and Brave - on Brave even 2 errors with exactly the same description
![image](https://user-images.githubusercontent.com/77065337/103834340-67f55000-5083-11eb-8848-77938db2547f.png)

**Comment by Lomet** [comment]
#66 is the same.

thanks for the report.
