### ISSUE TITLE
Wallet Connect Minor Bug

### ISSUE THREAD

**Issue by iSkylark** [The-Poolz/Poolz-Back#88]
**Describe the bug**
After connecting MetaMask wallet, when we click on "TomoChain" or "MoonBeam" tab and go back to Ethereum tab, MetaMask wallet gets disconnected and need to reconnect it. (see attached gif).

**To Reproduce**
1. Go to 'https://app.poolz.finance/dashboard'
2. Click on 'Connect a Wallet' and connect using MetaMask
3. Click on 'TomoChain' tab
4. Click on 'Ethereum' tab
5. See bug - need to connect wallet again.

**Expected behavior**
I expect Poolz to remember when wallet is already connected and switching tabs shouldn't disconnect it and require a user to reconnect it again and again every time they change chain.

**Screenshots**
![poolz1 - connect wallet](https://user-images.githubusercontent.com/77087043/103847754-e7af0900-50db-11eb-8c64-7711ad1daa79.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141 (Official Build) (64-bit)

**Wallet address**
0xC229eaB0B6D74E9D8BE4CCF4b22FBC7a46DCaE78

**Comment by Lomet** [comment]
this is the main issue #19 
thanks for the report.
