### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SerJo101** [The-Poolz/Poolz-Back#93]
**Describe the bug**
I found only one mistake and recorded it on video.

When I go to my investments section the Join button doesn't work, I click but nothing happens.
I recorded the error on video.

**Screenshots**
Video: https://drive.google.com/file/d/1boFb0dcXMkYmEawwCZBv-qekXeEiTk6J/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 87.0.4280.88

**Wallet address**
0x49B3db0fD5b98924d42dfad18A11C08f7d7A3e5F

**Comment by Lomet** [comment]
Thanks for the report. is here: https://github.com/The-Poolz/Poolz-Back/issues/24
