### ISSUE TITLE
Locked Deals not showing Bug

### ISSUE THREAD

**Issue by iSkylark** [The-Poolz/Poolz-Back#94]
**Describe the bug**
After adding Locked Deal to send token to other address, the Deal is not visible in the senders wallet. For example: 
I have created a Locked Deal to send 50TEST from wallet A to wallet B in 3 days time. That deal is not visible in wallet A, however is visible on wallet B. ( https://rinkeby.etherscan.io/tx/0xec0a66247c153c853d27b8eac1784e5b1bf55be8b1cc19c9d1f0b5f2aa20eedd )

I think that Wallet A should also see the deal he made, otherwise it will be confusing for users who created a deal, as they cannot check if creating a DEAL worked or not unless they check the transaction hash )may be complicated for non techy users).

**To Reproduce**
1. Go to 'https://app.poolz.finance/lockeddeal'
2. Click on 'Add Locked Deal'
3. In step 3, as 'Recipients Address' paste address of recipient (different than yours)
4. Create Pool
5. Among Locked Deals, the deal we just created is missing and we cannot check if it was created successfully.

**Expected behavior**
Created Locked Deal should be visible on Locked Deals tab. Next to the deal should be information if it was already claimed by the recipient or not and the recipients address.

**Screenshots**
<img width="952" alt="locke deal problem" src="https://user-images.githubusercontent.com/77087043/103872020-c4e71980-5108-11eb-9ce4-064716c13bf5.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87

**Wallet address**
0xC229eaB0B6D74E9D8BE4CCF4b22FBC7a46DCaE78

**Comment by Lomet** [comment]
the locked deal is not finished yet. (and not part of the bounty)
we can talk about it here: https://github.com/The-Poolz/Poolz-Back/issues/30
