### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tribarstudio** [The-Poolz/Poolz-Back#95]
**Describe the bug**
The site is not responsive to mobile devices and should be built with this in mind! I know this is technically a feature but the site should work seamlessly across all devices.

**To Reproduce**
1. Go to ' view the the site on mobile'

**Expected behavior**
The site should correctly respond to mobile and Tablet devices not only desktop for a improved UI/UX experience 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Wallet address**
0x88849a3Aa0d305f6Fa1EAC210477715FDA3e54A0

**Comment by Lomet** [comment]
we will add the mobile support at a later stage.
thanks for the report.
