### ISSUE TITLE
Orange Indicator instead of Red for a locked pool.

### ISSUE THREAD

**Issue by crypto-x-soldier** [The-Poolz/Poolz-Back#96]
**Describe the bug**
Orange indicator is shown instead of red for a locked pool.

**To Reproduce**
1. Go to 'https://app.poolz.finance/dashboard'
2. Click on 'Connect Wallet' and approve it in Metamask
3. Scroll down to Pool Id 7 for ChainLink Token. 

**Expected behavior**
The indicator should be red instead of Orange which is next to pool id

**Screenshots**
.![image](https://user-images.githubusercontent.com/77062578/103883094-bf86d080-5102-11eb-8231-e4181bb57db1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Vivaldi
 - Version : 3.5

**Wallet address**
0xdD5F5feE4Db473ACa5A0b52EE459Abd35D098BEE

**Comment by Lomet** [comment]
The orange is "Out of stock" status.
the pool is TLP with time left. 

now is red, after the time finish 
![image](https://user-images.githubusercontent.com/48094744/104578232-25270f80-5663-11eb-8289-f771c5ce76f7.png)
